// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "run":return img`
........................
...1111.................
..1....1................
.1.....1................
.1.....1................
.1.....1................
.1.....1................
.111111.................
.11.....................
.1.1.....1...1..1111....
.1..1....1...1..1...1...
.1...1...1...1..1...1...
.1....1..1...1..1...1...
.1.....1.1...1..1...1...
.1.....1..111...1...1...
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
